graphhopper:
  datareader.file: germany-latest.osm.pbf
  graph.location: graphs/germany/graph

  graph.flag_encoders: car
  prepare.ch.weightings: no
  prepare.lm.weightings: fastest
  prepare.lm.landmarks: 8

server:
  applicationConnectors:
  - type: http
    port: 8989
  adminConnectors:
  - type: http
    port: 8990

viewRendererConfiguration:
  freemarker:
    objectWrapper: DefaultObjectWrapper(2.3.28, exposeFields=true, iterableSupport=true)
